# https://taskfile.dev

version: "3"

tasks:
  build:
    cmds:
      - docker build -t cloud-enum-build .
      - docker run -it --rm -v ${PWD}:/usr/src/cloud-enum cloud-enum-build
      - docker build --platform=linux/amd64 -t cloud-enum-build .
      - docker run -it --rm -v ${PWD}:/usr/src/cloud-enum cloud-enum-build
      - pyinstaller --onefile --add-data=enum_tools/fuzz.txt:enum_tools --add-data=enum_tools/ns.txt:enum_tools -n cloud-enum-local-arm64 cloud_enum.py
